const animationLibrary = {
  masculine: {
    idle: [
      // 'M_Standing_Idle_001.glb',
      'M_Standing_Idle_002.glb',
      'M_Standing_Idle_Variations_001.glb',
    //   'M_Standing_Idle_Variations_002.glb',
    //   'M_Standing_Idle_Variations_003.glb',
    //   'M_Standing_Idle_Variations_004.glb',
    //   'M_Standing_Idle_Variations_005.glb',
    //   'M_Standing_Idle_Variations_006.glb',
      'M_Standing_Idle_Variations_007.glb',
      'M_Standing_Idle_Variations_008.glb',
      'M_Standing_Idle_Variations_009.glb',
      'M_Standing_Idle_Variations_010.glb',
    ],
    dance: [
      'M_Dances_001.glb',
      'M_Dances_002.glb',
      'M_Dances_003.glb',
      'M_Dances_004.glb',
      'M_Dances_005.glb',
    //   'M_Dances_006.glb',
    //   'M_Dances_007.glb',
    //   'M_Dances_008.glb',
    //   'M_Dances_009.glb',
    //   'M_Dances_010.glb',
    //   'M_Dances_011.glb',
    ],
    expression: [
      'M_Standing_Expressions_001.glb',
      'M_Standing_Expressions_002.glb',
      // 'M_Standing_Expressions_003.glb',
    //   'M_Standing_Expressions_004.glb',
    //   'M_Standing_Expressions_005.glb',
    //   'M_Standing_Expressions_006.glb',
    //   'M_Standing_Expressions_007.glb',
    //   'M_Standing_Expressions_008.glb',
    //   'M_Standing_Expressions_009.glb',
    //   'M_Standing_Expressions_010.glb',
    //   'M_Standing_Expressions_011.glb',
    //   'M_Standing_Expressions_012.glb',
    //   'M_Standing_Expressions_013.glb',
    //   'M_Standing_Expressions_014.glb',
    //   'M_Standing_Expressions_015.glb',
    //   'M_Standing_Expressions_016.glb',
    //   'M_Standing_Expressions_017.glb',
      'M_Talking_Variations_001.glb',
      'M_Talking_Variations_002.glb',
      'M_Talking_Variations_003.glb',
    //   'M_Talking_Variations_004.glb',
    //   'M_Talking_Variations_005.glb',
    //   'M_Talking_Variations_006.glb',
    //   'M_Talking_Variations_007.glb',
    //   'M_Talking_Variations_008.glb',
    //   'M_Talking_Variations_009.glb',
    //   'M_Talking_Variations_010.glb',
    ],
    // locomotion: [
    //   'M_Walk_Jump_001.glb',
    //   'M_Walk_Jump_002.glb',
    //   'M_Walk_Jump_003.glb',
    //   'M_Walk_Strafe_Left_001.glb',
    //   'M_Walk_Strafe_Right_001.glb',
    //   'M_Crouch_001.glb',
    //   'M_Crouch_Strafe_Right_001.glb',
    //   'M_Crouch_Walk_003.glb',
    //   'M_CrouchedWalk_Backwards_002.glb',
    //   'M_Falling_Idle_001.glb',
    //   'M_Jog_001.glb',
    //   'M_Jog_002.glb',
    //   'M_Jog_003.glb',
    //   'M_Jog_Backwards_001.glb',
    //   'M_Jog_Jump_001.glb',
    //   'M_Jog_Jump_002.glb',
    //   'M_Jog_Jump_003.glb',
    //   'M_Jog_Strafe_Left_001.glb',
    //   'M_Jog_Strafe_Right_001.glb',
    //   'M_Run_001.glb',
    //   'M_Run_Backwards_001.glb',
    //   'M_Run_Jump_001.glb',
    //   'M_Run_Jump_002.glb',
    //   'M_Run_Jump_003.glb',
    //   'M_Run_Strafe_Left_001.glb',
    //   'M_Run_Strafe_Right_001.glb',
    //   'M_Walk_001.glb',
    //   'M_Walk_002.glb',
    //   'M_Walk_003.glb',
    //   'M_Walk_Backwards_002.glb',
    // ],
  },
  feminine: {
    idle: [
      'F_Standing_Idle_001.glb',
    //   'F_Standing_Idle_002.glb',
    //   'F_Standing_Idle_003.glb',
    //   'F_Standing_Idle_004.glb',
    //   'F_Standing_Idle_005.glb',
      // 'F_Standing_Idle_006.glb',
      // 'F_Standing_Idle_007.glb',
      'F_Standing_Idle_Variations_001.glb',
    //   'F_Standing_Idle_Variations_002.glb',
    //   'F_Standing_Idle_Variations_003.glb',
      'F_Standing_Idle_Variations_004.glb',
    //   'F_Standing_Idle_Variations_005.glb',
    //   'F_Standing_Idle_Variations_006.glb',
      'F_Standing_Idle_Variations_007.glb',
    ],
    dance: [
      'F_Dances_001.glb',
    //   'F_Dances_002.glb',
    //   'F_Dances_003.glb',
      'F_Dances_004.glb',
      'F_Dances_005.glb',
      'F_Dances_006.glb',
      'F_Dances_007.glb',
    ],
    expression: [
      'F_Talking_Variations_001.glb',
    //   'F_Talking_Variations_002.glb',
      'F_Talking_Variations_003.glb',
    //   'F_Talking_Variations_004.glb',
      'F_Talking_Variations_005.glb',
    //   'F_Talking_Variations_006.glb',
      // 'F_Talking_Variations_007.glb',
    //   'F_Talking_Variations_008.glb',
    ],
    // locomotion: [
    //  'F_Crouch_001.glb',
    //   'F _Crouch_Strafe_Right_001.glb',
    //   'F_Crouch_Walk_001.glb',
    //   'F_CrouchedWalk_Backwards_001.glb',
    //   'F_Falling_Idle_001.glb',
    //   'F_Falling_001.glb',
    //   'F_Jog_001.glb',
    //   'F_Jog_Backwards_001.glb',
    //   'F_Jog_Jump_Small_001.glb',
    //   'F_Jog_Strafe_Left_001.glb',
    //   'F_Jog_Strafe_Right_001.glb',
    //   'F_Run_001.glb',
    //   'F_Run_Backwards_001.glb',
    //   'F_Run_Jump_001.glb',
    //   'F_Run_Strafe_Left_001.glb',
    //   'F_Run_Strafe_Right_001.glb',
    //   'F_Walk_001.glb',
    //   'F_Walk_002.glb',
    //   'F_Walk_Backwards_001.glb',
    //   'F_Walk_Jump_001.glb',
    //   'F_Walk_Strafe_Left_001.glb',
    //   'F_Walk_Strafe_Right_001.glb',
    // ],
  },
};

export default animationLibrary;
